email = "LuxChain <program.python.test@gmail.com>"
password = "Nova2023!"
username = "program.python.test@gmail.com"
app_password = "ujweanmungpxlahc"
# waitlist_username = "customersupport@luxorawallet.io"
# waitlist_email = "LuxoraWallet <customersupport@luxorawallet.io>"
# waitlist_app_password = "rkbbupfowvkgllxg"

# contact_username = "luxorawaitlist@luxorawallet.io"
# contact_email = "LuxoraWaitlist <luxorawaitlist@luxorawallet.io>"
# contact_app_password = "dkpxvdxhseyrquhp"